node {
  stage 'build in development'
  openshiftBuild(namespace: 'dev', buildConfig: 'simpledemo', showBuildLogs: 'true')
  
  stage 'deploy in development'
  openshiftDeploy(namespace: 'dev', deploymentConfig: 'simpledemo')
  openshiftTag(namespace: 'dev', sourceStream: 'simpledemo',  sourceTag: 'latest', destinationStream: 'simpledemo', destinationTag: 'promoteToQA', destinationNamespace: 'dev')

  stage 'deploy in QA'
  openshiftDeploy(namespace: 'qa', deploymentConfig: 'simpledemo )

  stage 'scale dev and QA'
  openshiftScale(namespace: 'dev', deploymentConfig: 'simpledemo',replicaCount: '2')
  openshiftScale(namespace: 'qa', deploymentConfig: 'simpledemo',replicaCount: '3')
}
