apiVersion: v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: | 
        node {
          stage 'checkout'
          git 'https://github.com/samueltauil/pipelines.git'
          
          stage 'maven build'
          withMaven(maven: 'M3') {
           sh "mvn clean install"
          } 
        }
  output:
  resources:
  postCommit:
