apiVersion: v1
kind: BuildConfig
metadata:
  name: samplepipeline
  app: pipelines 
  labels:
    name: samplepipeline
spec:
  runPolicy: Serial
  source:
    type: "Git"
    git:
      uri: "https://github.com/samueltauil/pipelines.git"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: resources/Jenkinsfile 
  output:
  resources:
  postCommit:
